### ISSUE TITLE
プラグイン: DragFoldTool (折りツール)

### ISSUE THREAD

**Issue by mino-ri** [mino-ri/Orimath#3]
## 概要

紙上をドラッグすることで折線をつけたり折り畳んだりするツール。

## 機能

左ドラッグ … AとBを重ねるように折る
右ドラッグ … AとBを(線の場合は垂直に)通るように折る
左クリック … 基準点として選択
Alt … 自由折り

- [x] 公理1 (点から点へ右ドラッグ)
- [x] 公理2 (点から点へ左ドラッグ)
- [x] 公理3 (線から線へ左ドラッグ)
- [x] 公理4 (点から線へ右ドラッグ)
- [x] 公理5 (1点を選択し、点から線へ左ドラッグ)
- [x] 公理6 (1点と1線を選択し、点から線へ左ドラッグ)
- [x] 公理7 (1線を選択し、点から線へ左ドラッグ)
- [x] 非公理的な折り方 (何も選択せず点から線へ左ドラッグ)
- [x] 自由折り (Altキーを押しながらドラッグ)
- [x] 折り線をつける
- [x] 折り返す (Shiftキー)
- [x] 折り図表示

**Comment by kei-morisue** [comment]
すてきUI 設計です！
（イシュー管理もちゃんとして偉い...）
